project: default
source:
    values: |-
      postgresql:
        enabled: false
        postgresqlHost: "postgresql"
        postgresqlUser: "wiki"
        postgresqlDatabase: "wiki"
        existingSecret: "wiki-postgresql-password"
        existingSecretKey: "postgresql-password"

